FROM jupyterhub/singleuser:0.9.4

## =============================================================
## base - image ... whatever functionality you want to provide !
## This is my unix / python stuff (but it doesn't have underworld)
##
## This dockerfile builds an image from this content, and serves the
## sample web pages and notebooks at port 8080
##
## docker run -p 8181:8080 --name="docker-web-notebooks-test" -t lmoresi/lmoresi/docker-web-notebooks-module
## and then browse the docker VM ip address on port 8181 (for example)
##
## OR just use kitematic and click on the preview image
##
## =============================================================

USER root

# The following installations are required for:
# various: build-essential
# stripy: gcc,  gfortran
# lavavu: libgl*mesa*, libpng-dev, libtiff-dev, libx11-dev
# lavavu: freeglut*, xvfb


RUN apt-get update -y ;
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --fix-missing \
        gcc gfortran \
        libpng-dev \
        libtiff-dev \
        libx11-dev \
        build-essential \
        libgl1-mesa-dri \
        libgl1-mesa-glx \
        freeglut3 \
        freeglut3-dev \
        xvfb \
        git \
        && conda install -y numpy scipy cartopy gdal netcdf4 obspy \
        && rm -rf /var/lib/apt/lists/*

#

RUN pip install stripy
RUN pip install git+https://github.com/OKaluza/LavaVu.git --user

RUN addgroup jovyan  || true
RUN usermod -a -G jovyan jovyan || true
RUN chown -R jovyan:jovyan /home/jovyan/.local


# RUN useradd --create-home --home-dir /home/jovyan --shell /bin/bash --user-group jovyan || true

# # Install Tini.. this is required because CMD (below) doesn't play nice with notebooks for some reason: https://github.com/ipython/ipython/issues/7062, https://github.com/jupyter/notebook/issues/334
# RUN curl -L https://github.com/krallin/tini/releases/download/v0.10.0/tini > tini && \
#     echo "1361527f39190a7338a0b434bd8c88ff7233ce7b9a4876f3315c22fce7eca1b0 *tini" | sha256sum -c - && \
#     mv tini /usr/local/bin/tini && \
#     chmod +x /usr/local/bin/tini

# script for xvfb-run.  all docker commands will effectively run under this via the entrypoint
RUN printf "#\041/bin/sh \n rm -f /tmp/.X99-lock && xvfb-run -s '-screen 0 1600x1200x16' \$@" >> /usr/local/bin/xvfbrun.sh && \
                    chmod +x /usr/local/bin/xvfbrun.sh



RUN mkdir -p /home/user_data && chmod +rx /home/user_data && chown jovyan:jovyan /home/user_data
WORKDIR  /home/user_data/

## These are the build templates etc
ADD --chown=jovyan:jovyan  CourseContent/Data/Reference Data/Reference
ADD --chown=jovyan:jovyan  CourseContent/Data/Resources Data/Resources

# Would be useful to have this extension and should load this all earlier

RUN pip install litho1pt0
RUN pip install jupyter-server-proxy
RUN jupyter labextension install jupyterlab-server-proxy
RUN jupyter labextension install @jupyterlab/git
RUN jupyter labextension install @jupyterlab/hub-extension
RUN pip install jupyterlab-git
RUN jupyter serverextension enable --py jupyterlab_git  --sys-prefix
RUN pip install lavavu==1.2.55
RUN pip install imageio

# Put this here as the notebooks change often

ADD --chown=jovyan:jovyan  CourseContent/Notebooks      Notebooks
ADD --chown=jovyan:jovyan  Docker/Kub-JHub/install_notebooks.py scripts/install_notebooks.py


USER jovyan

# Persistent / Shared space outside the container
# VOLUME /home/jovyan/Data/Resources
# VOLUME /home/jovyan/build

# expose notebook port and server port
EXPOSE 8888

# This ensures that the notebooks can run in a stand-alone container
# In the normal way this will be nuked by the hub mount of /home/jovyan

RUN mkdir -p /home/jovyan/PYE_2019
RUN ln -s /home/user_data/Notebooks /home/jovyan/PYE_2019/Notebooks
RUN ln -s /home/user_data/Data      /home/jovyan/PYE_2019/Data
WORKDIR  /home/jovyan/


# note we use xvfb which to mimic the X display for lavavu
ENTRYPOINT ["/usr/local/bin/xvfbrun.sh"]

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''", "--default_url=/lab/tree/PYE_2019/Notebooks/0-StartHere.ipynb" ]
